version: '3.5'
services:
  web:
    platform: "linux/amd64"
    build: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://vetcaredb.mysql.database.azure.com:3306/vetcare_db
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: V3tC@re_DB2024
    depends_on:
      database:
        condition: service_healthy

  database:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vetcare_db
      MYSQL_ROOT_PASSWORD: V3tC@re_DB2024
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$root --password=$$V3tC@re_DB2024
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - 9000:8080
       
volumes:
  db:
